Repository CSID-DGU/2023-1-OSSP2-DALL-E-noway-2, pull requests merged in 2023-05, with the labels that each got.

#4 [FE] vue 프로젝트 생성 및 스캐폴딩
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.prettierrc
  frontend/.vscode/extensions.json
  frontend/README.md
  frontend/env.d.ts
  frontend/index.html
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/assets/base.css
  frontend/src/assets/logo.svg
  frontend/src/assets/main.css
  frontend/src/components/common/HeaderBar.vue
  frontend/src/components/common/NavBar.vue
  frontend/src/components/icons/IconCommunity.vue
  frontend/src/components/icons/IconDocumentation.vue
  frontend/src/components/icons/IconEcosystem.vue
  frontend/src/components/icons/IconSupport.vue
  frontend/src/components/icons/IconTooling.vue
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/stores/counter.ts
  frontend/src/views/BoardListView.vue
  frontend/src/views/BoardView.vue
  frontend/src/views/BookmarkView.vue
  frontend/src/views/CalendarView.vue
  frontend/src/views/CommentView.vue
  frontend/src/views/DreamDiaryFeedView.vue
  frontend/src/views/DreamDiaryView.vue
  frontend/src/views/LikeView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/NewBoardView.vue
  frontend/src/views/NewDreamDiaryView.vue
  frontend/src/views/NotFoundView.vue
  frontend/src/views/ProfileEditView.vue
  frontend/src/views/ProfileView.vue
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: FE, FEAT

#8 [COMMON] 로컬 개발환경 설정
  .gitattributes
  .gitignore
  docker-compose.yaml
  frontend/vite.config.ts
  mariadb/.gitkeep
  mariadb/dalle.sql
  nginx/Dockerfile
  nginx/nginx.conf
Labels: COMMON, environment

#9 [BE] FEAT: OAuth 로그인 및 인증 구현
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/google/google.guard.ts
  backend/src/auth/google/google.strategy.ts
  backend/src/auth/jwt/jwt.auth.guard.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/auth/kakao/kakao.guard.ts
  backend/src/auth/kakao/kakao.strategy.ts
  backend/src/auth/mock/mock.user.service.ts
  backend/src/auth/naver/naver.guard.ts
  backend/src/auth/naver/naver.strategy.ts
  backend/src/config/configuration.ts
  backend/src/decorator/google.user.decorator.ts
  backend/src/decorator/kakao.user.decorator.ts
  backend/src/decorator/naver.user.decorator.ts
  backend/src/decorator/user.decorator.ts
  backend/src/dto/user.dto.ts
  backend/src/main.ts
  backend/src/type/social.profile.ts
  backend/src/user/interface/user.service.interface.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  backend/yarn.lock
Labels: BE, FEAT

#10 [FE] FEAT: tailwind 설치 및 설정 적용
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/index.css
  frontend/src/main.ts
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: FE, FEAT

#12 [BE] ORM 매핑 및 DB 연동
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/configuration.ts
  backend/src/config/typeorm.config.ts
  backend/src/entities/board.entity.ts
  backend/src/entities/bookmark.entity.ts
  backend/src/entities/category.entity.ts
  backend/src/entities/comment.entity.ts
  backend/src/entities/diary.category.entity.ts
  backend/src/entities/diary.stat.category.entity.ts
  backend/src/entities/diary.stat.entity.ts
  backend/src/entities/dream.diary.entity.ts
  backend/src/entities/favorite.entity.ts
  backend/src/entities/follow.entity.ts
  backend/src/entities/oauth.entity.ts
  backend/src/entities/user.entity.ts
  backend/src/enum/board.type.ts
  backend/src/enum/disclosure.scope.type.ts
  backend/src/enum/filter.type.ts
  backend/src/enum/provider.type.ts
  backend/yarn.lock
Labels: BE, FEAT

#15 [FE] FEAT: 로그인 구현
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/api/axios.instance.ts
  frontend/src/api/cookie/index.ts
  frontend/src/assets/images/google-login.png
  frontend/src/assets/images/kakao-login.png
  frontend/src/assets/images/naver-login.png
  frontend/src/components/common/HeaderBar.vue
  frontend/src/components/login/GoogleLoginButton.vue
  frontend/src/components/login/KakaoLoginButton.vue
  frontend/src/components/login/NaverLoginButton.vue
  frontend/src/index.css
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/views/LoginView.vue
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: FE, FEAT

#13 [BE] FEAT: 유저 정보를 DB에 저장하는 기능 추가
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  backend/yarn.lock
Labels: BE, FEAT

#19 [BE] BUG: 토큰 생성 시 에러 발생 수정
  backend/src/auth/auth.service.ts
  backend/src/user/user.service.ts
Labels: bug, BE

#23 [BE] FEAT: 댓글 기능 구현
  backend/src/app.module.ts
  backend/src/comment/comment.controller.spec.ts
  backend/src/comment/comment.controller.ts
  backend/src/comment/comment.module.ts
  backend/src/comment/comment.service.spec.ts
  backend/src/comment/comment.service.ts
  backend/src/decorator/user.decorator.ts
  backend/src/dto/comment.dto.ts
  backend/src/dto/comment.request.dto.ts
  backend/src/dto/comment.response.dto.ts
  backend/src/entities/comment.entity.ts
  mariadb/dalle.sql
Labels: BE, FEAT

#38 [FE] FEAT: 꿈 일기 이미지 생성 뷰 구현
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/configuration.ts
  backend/src/dreamdiary/dreamdiary.controller.ts
  backend/src/dreamdiary/dreamdiary.module.ts
  backend/src/dreamdiary/dreamdiary.service.ts
  backend/src/dto/generate.dreamdiary.images.request.dto.ts
  backend/src/dto/generated.images.response.dto.ts
  backend/src/entities/image.requests.entity.ts
  backend/src/entities/user.entity.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  backend/src/util/openai.service.ts
  backend/src/util/system.scheduler.ts
  backend/src/util/util.module.ts
  backend/yarn.lock
  frontend/src/api/axios.custom.ts
  frontend/src/components/common/HeaderBar.vue
  frontend/src/components/dreamDiary/BlackBGButton.vue
  frontend/src/components/dreamDiary/CategorySelect.vue
  frontend/src/components/dreamDiary/DisclosureScopeSelect.vue
  frontend/src/components/dreamDiary/StarRating.vue
  frontend/src/components/dreamDiary/WhiteBGButton.vue
  frontend/src/components/icons/IconGoBack.vue
  frontend/src/router/index.ts
  frontend/src/stores/diary.create.store.ts
  frontend/src/types/dto/dreamdiary.create.request.dto.ts
  frontend/src/types/enum/disclosure.scope.ts
  frontend/src/types/index.ts
  frontend/src/views/FollowView.vue
  frontend/src/views/GenerateImageView.vue
  frontend/src/views/NewDreamDiaryView.vue
  mariadb/dalle.sql
Labels: FE, FEAT

#32 [FE] FEAT: 헤더바에 뒤로가기 버튼 조건부 추가
  frontend/src/components/common/HeaderBar.vue
  frontend/src/components/icons/IconGoBack.vue
  frontend/src/router/index.ts
  frontend/src/views/FollowView.vue
  frontend/src/views/GenerateImageView.vue
Labels: FE, FEAT

#42 [BE] FIX: 프로필 업데이트 이미지 업로드 로직 수정
  .gitignore
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/configuration.ts
  backend/src/dto/profile.update.request.dto.ts
  backend/src/profile/profile.controller.ts
  backend/src/profile/profile.service.ts
  backend/yarn.lock
Labels: BE, FEAT, fix

#45 [BE] FEAT: 자기 자신의 정보를 조회하는 API 추가
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
Labels: BE, FEAT
