Repository CSID-DGU/2023-1-OSSP2-DALL-E-noway-2, pull requests merged in 2023-06, with the labels that each got.

#54 [COMMON] nginx uploads 경로 proxy_pass 추가 필요
  nginx/nginx.conf
Labels: bug, COMMON

#52 [FE] 프로필 뷰 구현
  backend/src/dto/follow.user.response.dto.ts
  backend/src/profile/profile.controller.ts
  backend/src/profile/profile.service.ts
  frontend/package.json
  frontend/src/api/axios.custom.ts
  frontend/src/components/common/NavBar.vue
  frontend/src/components/icons/IconCoin.vue
  frontend/src/components/profile/ProfileBar.vue
  frontend/src/router/index.ts
  frontend/src/stores/my.info.store.ts
  frontend/src/stores/profile.store.ts
  frontend/src/types/enum/follow.type.ts
  frontend/src/types/index.ts
  frontend/src/views/DreamDiaryFeedView.vue
  frontend/src/views/FollowView.vue
  frontend/src/views/ProfileDetailView.vue
  frontend/src/views/ProfileEditView.vue
  frontend/src/views/ProfileView.vue
  frontend/yarn.lock
Labels: FE, FEAT

#58 [FE] 댓글 뷰 기능 구현
  frontend/src/api/axios.custom.ts
  frontend/src/components/icons/IconSend.vue
  frontend/src/components/icons/IconThreeDots.vue
  frontend/src/router/index.ts
  frontend/src/views/CommentView.vue
Labels: help wanted, FE, FEAT

#66 [COMMON] 달력 API, 뷰 구현 && 일기 피드 관련 수정
  backend/src/dreamdiary/calendar/calendar.controller.ts
  backend/src/dreamdiary/calendar/calendar.module.ts
  backend/src/dreamdiary/calendar/calendar.service.ts
  backend/src/dreamdiary/dreamdiary.controller.ts
  backend/src/dreamdiary/dreamdiary.module.ts
  backend/src/dreamdiary/dreamdiary.service.ts
  backend/src/dto/calendar.day.info.dto.ts
  backend/src/dto/calendar.list.response.dto.ts
  backend/src/dto/dreamdiary.feed.dto.ts
  backend/src/dto/dreamdiary.feeds.response.dto.ts
  backend/src/profile/profile.service.ts
  frontend/src/api/axios.custom.ts
  frontend/src/components/calendar/CalendarPagination.vue
  frontend/src/components/calendar/CalendarWeek.vue
  frontend/src/components/common/LoadingAnimation.vue
  frontend/src/components/icons/IConChevron.vue
  frontend/src/stores/calendar.info.store.ts
  frontend/src/types/index.ts
  frontend/src/utils/local.storage.ts
  frontend/src/views/CalendarView.vue
Labels: BE, FE, FEAT, fix

#68 [COMMON] 일기 생성, 게시글 생성 API 연동
  backend/dummy
  backend/package-lock.json
  backend/package.json
  backend/src/board/board.controller.ts
  backend/src/board/board.service.ts
  backend/src/category/category.controller.ts
  backend/src/dreamdiary/dreamdiary.controller.ts
  backend/src/dreamdiary/dreamdiary.service.ts
  backend/src/dto/post.request.dto.ts
  backend/yarn.lock
  frontend/src/api/axios.custom.ts
  frontend/src/components/dreamDiary/CategorySelect.vue
  frontend/src/components/dreamDiary/StarRating.vue
  frontend/src/stores/category.info.store.ts
  frontend/src/stores/diary.create.store.ts
  frontend/src/views/DreamDiaryFeedView.vue
  frontend/src/views/NewDreamDiaryView.vue
  frontend/src/views/NewPostView.vue
  package-lock.json
  yarn-error.log
Labels: BE, FE, FEAT, fix

#69 [FE] 댓글 API 변경사항 반영
  frontend/src/api/axios.custom.ts
  frontend/src/views/CommentView.vue
Labels: FE, fix

#67 [BE] FEAT: 꿈일기,기타게시판 좋아요 즐겨찾기 목록 구현
  backend/src/app.module.ts
  backend/src/dto/likebookmark.boards.response.dto.ts
  backend/src/dto/likebookmark.diary.response.dto.ts
  backend/src/likebookmarklist/likebookmarklist.controller.ts
  backend/src/likebookmarklist/likebookmarklist.module.ts
  backend/src/likebookmarklist/likebookmarklist.service.ts
Labels: BE, FE

#79 [COMMON] 최초 로그인 시 프로필 설정하는 기능 추가
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/dreamdiary/dreamdiary.service.ts
  backend/src/user/user.service.ts
  frontend/src/components/profile/ProfileBar.vue
  frontend/src/components/profile/ProfileEdit.vue
  frontend/src/stores/profile.store.ts
  frontend/src/types/index.ts
  frontend/src/views/DreamDiaryFeedView.vue
  frontend/src/views/ProfileDetailView.vue
Labels: BE, FE, FEAT

#87 [FE] 댓글 목록에서 답글이 댓글 밑에 달리도록 수정
  frontend/src/views/CommentView.vue
Labels: FE, fix

#88 [FE] 통계 정보 컴포넌트 구현
  backend/src/app.module.ts
  backend/src/dreamdiary/calendar/stat/stat.controller.ts
  backend/src/dreamdiary/calendar/stat/stat.module.ts
  backend/src/dreamdiary/calendar/stat/stat.service.ts
  backend/src/dreamdiary/dreamdiary.service.ts
  backend/src/dto/stat.category.count.response.dto.ts
  backend/src/dto/stat.score.avg.response.dto.ts
  backend/src/dto/stat.total.score.avg.dto.ts
  backend/src/entities/diary.category.entity.ts
  backend/src/entities/dream.diary.entity.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/axios.custom.ts
  frontend/src/components/calendar/AverageBarStat.vue
  frontend/src/components/calendar/CountPieStat.vue
  frontend/src/components/calendar/ScoreBarStat.vue
  frontend/src/stores/calendar.info.store.ts
  frontend/src/types/index.ts
  frontend/src/views/CalendarView.vue
  frontend/yarn.lock
Labels: bug, BE, FE, FEAT

#85 [BE] 꿈일기 통계 API 구현
  backend/src/app.module.ts
  backend/src/dreamdiary/calendar/stat/stat.controller.ts
  backend/src/dreamdiary/calendar/stat/stat.module.ts
  backend/src/dreamdiary/calendar/stat/stat.service.ts
  backend/src/dto/stat.category.count.response.dto.ts
  backend/src/dto/stat.score.avg.response.dto.ts
  backend/src/dto/stat.total.score.avg.dto.ts
  backend/src/entities/diary.category.entity.ts
  backend/src/entities/dream.diary.entity.ts
Labels: BE, FEAT

#84 [BE] 일기 이미지 생성 프롬프트 개선
  backend/src/dreamdiary/dreamdiary.controller.ts
  backend/src/dreamdiary/dreamdiary.service.ts
  backend/src/dto/generate.dreamdiary.images.request.dto.ts
  backend/src/util/openai.service.ts
  frontend/src/api/axios.custom.ts
  frontend/src/views/GenerateImageView.vue
Labels: enhancement, BE

#93 [FE] 프로필 뷰에서 꿈일기 피드, 게시글 목록 구현
  frontend/src/api/axios.custom.ts
  frontend/src/types/enum/filter.type.ts
  frontend/src/types/index.ts
  frontend/src/views/ProfileView.vue
Labels: FE, FEAT

#97 [FE] FIX: 기타 개선사항 반영
  frontend/src/components/common/LoadingAnimation.vue
  frontend/src/router/index.ts
  frontend/src/views/FollowView.vue
  frontend/src/views/GenerateImageView.vue
Labels: FE, fix

#98 [BE] 일기 이미지 생성 프롬프트 개선
  backend/src/util/openai.service.ts
Labels: enhancement, BE

#99 [COMMON] 일기 이미지 생성, 이미지 파일 경로 관련 버그 수정
  backend/src/board/board.controller.ts
  backend/src/dreamdiary/dreamdiary.controller.ts
  backend/src/dto/generated.images.response.dto.ts
  backend/src/profile/profile.controller.ts
  backend/src/util/openai.service.ts
  frontend/src/api/axios.custom.ts
  frontend/src/stores/diary.create.store.ts
  frontend/src/types/index.ts
  frontend/src/views/DreamDiaryFeedView.vue
  frontend/src/views/DreamDiaryView.vue
  frontend/src/views/GenerateImageView.vue
  frontend/src/views/NewDreamDiaryView.vue
Labels: bug, BE, FE

#104 [COMMON] 팔로우 관련 API 및 뷰 수정
  backend/src/dto/follow.user.dto.ts
  backend/src/dto/follow.user.response.dto.ts
  backend/src/dto/profile.follow.response.dto.ts
  backend/src/profile/profile.controller.ts
  backend/src/profile/profile.service.ts
  frontend/src/api/axios.custom.ts
  frontend/src/views/FollowView.vue
Labels: BE, FE, fix
